# Generated by Django 5.0.4 on 2024-05-11 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_remove_flower_price_flower_price_l_flower_price_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_id', models.IntegerField()),
                ('flower_size', models.CharField(choices=[('S', 'S'), ('M', 'SM'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('S M', 'S M'), ('M L', 'M L'), ('L XL', 'L XL'), ('XL XXL', 'XL XXL'), ('S M L', 'S M L'), ('M L XL', 'M L XL'), ('L XL XXL', 'L XL XXL'), ('S M L XL', 'S M L XL'), ('M L XL XXL', 'M L XL XXL'), ('S M L XL XXL', 'S M L XL XXL')], max_length=12)),
                ('flower_num', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
